language: java
jdk: openjdk11
os: linux

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Ddockerfile.skip=true -B -V

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "EfXQvvC7t/NLZBQrDBydfzzeM7BVZfx90lgebMMh7/m0aWwwa00FvKKjxuSCEA4YvRTLmBq0q82vmBBmM7mKvbB+m8xcoFPH+1L2F0d8LNfuu1+k1i9gYvAtOOhFDtA0UUzePIgab9htOpImpBU5WrV1A1hKTVpwdmWkSBZaVYmxGgtdRZqXW+X54oI8Qn9i9tvo8Tnx7TR6ZvIZqQcQ7uII0PDTMSY8Ze9Y03B3G1Vvfri1GDDia5eQf1KJ0aVuw9uO/9scrGUa2VtzxE9iNi6bjRbmMh2GCETm98NktV5lhZrLB4jWZU28znvNVMknMVjXPRgYscVsxpqj82w9lyrD47TPK4mH+FwiH3k5fMVDec6AURe3VKf7bWqts2ywU305yQJx7nfMQTNCbVqDs4Z5hOv7vIfUp5D2h13dOgmdSBR3GhNfXgdGc2SW7BKhEnzAYktsI4zQnghqXDuZQ6T9hJDFuKxqxGoxOYTp76jSbmv8iwrTVYJ8ZF8TokD3jU4Swa6aRObNIbsElu55Ot51zxpOxhym13UfuN0EswJaNAFIHlneMYt4O9K+czkGbRKC+FUhZBC0a5mq8NHNzrNMHRfNUvsvyOSUCVu51c5uERn2mgJ4b8hS7fCJG5BG3cQYW2R+CSyxttwlHC/hvcMcUGSbOrTEVIGFdskyofM="
  secret_access_key:
    secure: "Q4nQ/ms24AJhPPe9/E/PtjsieNNaBGT6ZsthkhgbQRMUDU6SCRMUR+4bK6AJoD7NTqI3urGUfrRBChp92IRYx747TU50Ujoe7sxUGw+pu1ISqdo3TB5rCH9Qbeh9HBqKQPqYUGjPl/zXY/5b65AKGuEPZNpuXB2oFgrRKfUH/aSUyDbIcfM2AvAy2w7bF+Fb+Q5v5gQudIJKZ3V3sFrlnck3+ZIr/tl4yLUoA+qjzH5otM+MQVXomM95wW6Ew/IC7v3yPTESb2LwOxNyft2jnIqto9JoNuIizeiOG9kJJkUY9W8QFJ7BsBuFK4lTLwkrQFssvxxEKrFSbCf8CmxOIOsSIWqCP2F4zeq29+oiQX3fWC2XFLE3PMp6MZ/dQUYub1WrXuATXK4Z0aNOanvycWWPcbFv4WYx4uW9vp9BSwMR7Qz2AjTRK5erLcAnyZglGIY8WlkhDnyoxcba8LqSGEOrmpr6aekRLo0fAGywWNSGxEtqZqxNpzhu+9JGBzRCPGeeWIYswuNIiG9Me04mvg4UGeh3wSpt1UYQ8D8l2vEq1bNf2rKa4YWtSpz0Mtlr83QaS9/0tabBhrplnH2OJrIZl/Mv9dIU+rCux1SBi0ifpECp3AfxxCIdnF4rx2Fe4Hco3GbuEhRSPZ5CD5OMM8EahozYXr8pfDt1dab6gf8="
  region: "us-east-2"
  app: "2-env"
  env: "2Env-env"
  bucket_name: "aws-quickstart-vlad"
  skip_cleanup: "true"