language: java
jdk: openjdk11
os: linux

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Ddockerfile.skip=true -B -V

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "tinvCJcw5moyO7KCltOopQ8YdtI9e3bLaBDHb5XnfikF+Tuo6ZzR0gz96tBcUeDg1FY9XI2XLrfVle6Gw0u9EnxzM2LqZgvuGDi7hGWXHSN0W6UJ6wwHWH0EEY5g1jk9Ii0CsCksupiAObt/kTlP8GJufwEKBCtZYmbo94GEqE2Eb9wGRcStYmwacsMlzxOHDL0ZKEcv+7/bWP0l7rcJgXhPD5SZ3gntysZnMaNaxMurqI+Ld9WeoheE99sy1aaj6MWp1OO9fbrK1bcx4LMkQ1T+rLhw8iWjeY+PTqKtQ40FQB/5nu6dbSxueWR6TAjmumWKiT+vGqoUy99W9FQlB1K4/spAU/+8OZnwjMOG5Jn0TByqO/4h2kjjmE6e8HcBGJiQD9N48Kygr9zK5zXpWT1AmI6ngwL8H9sCaufLZ3Wb8Hub9qfloBVA9/aptuEZVts2VC8w34c/onhlxTFx5HeIRJHx8JqjZlfYglLGO18AuAAEKpf8WicFgwCHyR8Ktez/y+1Fq/q7z3UF1fNKSOLa9jDwfuFzX6k1cNitiU2iNZtQVBkTSH73H33L1C+6+PhgU0Xxd6PaoiIjrlu9K6HNckkfbPKHHR5Bomzk1CJ8luLwo8mNRk6CquKzcTciHNt5IU39PWC335kTnd9LpXr9XAdpufDcq0U3ud9in1c="
  secret_access_key:
    secure: "KvvoLNV/fqpn+hmHJDogS48b14BRDdH7V4Z4aSbfOUk9XgNvRr1OF8L4wp9yFm1zSKujSTNkoviDIkNEIk9uLthf4t0W3oN9N7Up30UBFTRHUHoKBI7qQS3gjQGYAZ3yj5gfhOMYrWrVPUfYdZ9b+C1BalUbMaWnQNns2DODTA/3ztV/u/Fni/3Br2z/oOqtJK9LncMsXM8koiXbpDlla3ijVGJOP3+1LRYoVNd/8Fv7PyjqLj7X5j/AcmIq0wrSMX5SfjUM9ZfXAd2/ydv0hyoUF+jz2F4JQJWXrijqab9e97es/iFoxCk3lbm4yyQ5ARpOnCzPad3CHQRFQuQF3H18GY23zruDe5tcIMvzdHvnuVENhtZSCJm/uHWEqIrAl5s3K2mihIPZ71yx03VzoNE9X3buEZQSxaWpi2wai9Xmt//Ofot63gh+L0RpF112uVQCFknE16jCHC6AbsXswHV1h5/toSxLYXC8DYr2I3dI5TTTI0YLO5+5hZAJSEBOCLHDZxuA4paGPj+I7Xkoo8cJalFnr95w7o0duW2PD6tNKTzqWUKirsgYP/VXEQWt5UDnFeI3dDWXOnOuBgS+Cbi93R6E94W+uc/0SrB3zci7AaQZGif+JEwsHRg38zvMlPPE0OWQcy3zIFgLguOFl0cFFnVsRl0+lRZeQkHZ1wY="
  region: "us-east-2"
  app: "example-app-name"
  env: "2-env"
  bucket_name: "aws-quickstart-vlad"
  skip_cleanup: "true"